name: postgres-nest

services:
  database:
    image: postgres:17.2-bullseye
    container_name: postgres-nest-jwt
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: postgres
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
